import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';
import LanguageDetector from 'i18next-browser-languagedetector';

i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
        debug: true,
        fallbackLng: 'en',
        interpolation: {
            escapeValue: false, // not needed for react as it escapes by default
        },
        resources: {
            en: {
                translation: {
                    common: {
                        loading: "Loading...",
                        analyzing: "Analyzing...",
                        dashboard: "Dashboard",
                        clients: "Clients",
                        items: "Items & Services",
                        purchases: "Purchases",
                        analyze: "Analyze",
                        logout: "Logout",
                        profile: "Profile",
                        settings: "Settings",
                        search: "Search...",
                        add: "Add",
                        cancel: "Cancel",
                        save: "Save",
                        delete: "Delete",
                        edit: "Edit",
                        actions: "Actions",
                        no_data: "No data available",
                        select_client: "Select Client...",
                    },
                    analyze: {
                        title: "AI Analysis",
                        subtitle: "Unlock insights into customer behavior with predictive analytics.",
                        total_spent: "Total Spent",
                        total_purchases: "Total Purchases",
                        spending_history: "Spending History",
                        top_items: "Top Items",
                        ai_insights: "AI Psychological Profile & Strategy",
                        generated_by: "Generated by Ollama (gpt-oss:20b) - English",
                        analyze_button: "Analyze",
                    },
                    clients: {
                        title: "Clients",
                        subtitle: "Manage your client base.",
                        add_client: "Add Client",
                        name: "Name",
                        email: "Email",
                        phone: "Phone",
                        address: "Address",
                    },
                }
            },
            ar: {
                translation: {
                    common: {
                        loading: "جاري التحميل...",
                        analyzing: "جاري التحليل...",
                        dashboard: "لوحة التحكم",
                        clients: "العملاء",
                        items: "المنتجات والخدمات",
                        purchases: "المشتريات",
                        analyze: "تحليل الذكاء الاصطناعي",
                        logout: "تسجيل الخروج",
                        profile: "الملف الشخصي",
                        settings: "الإعدادات",
                        search: "بحث...",
                        add: "إضافة",
                        cancel: "إلغاء",
                        save: "حفظ",
                        delete: "حذف",
                        edit: "تعديل",
                        actions: "إجراءات",
                        no_data: "لا توجد بيانات متاحة",
                        select_client: "اختر عميل...",
                    },
                    analyze: {
                        title: "تحليل الذكاء الاصطناعي",
                        subtitle: "اكتشف رؤى حول سلوك العملاء من خلال التحليلات التنبؤية.",
                        total_spent: "إجمالي الإنفاق",
                        total_purchases: "إجمالي المشتريات",
                        spending_history: "تاريخ الإنفاق",
                        top_items: "أكثر المنتجات شراءً",
                        ai_insights: "الملف النفسي والاستراتيجية (AI)",
                        generated_by: "تم إنشاؤه بواسطة Ollama (gpt-oss:20b) - العربية",
                        analyze_button: "تحليل",
                    },
                    clients: {
                        title: "العملاء",
                        subtitle: "إدارة قاعدة عملائك.",
                        add_client: "إضافة عميل",
                        name: "الاسم",
                        email: "البريد الإلكتروني",
                        phone: "الهاتف",
                        address: "العنوان",
                    },
                }
            }
        }
    });

export default i18n;
